import Item from "./Item.js";

const fish = [
  new Item("鮫", "さめ", "shark", "same.png", "https://ja.wikipedia.org/wiki/サメ"),
  new Item("鰻", "うなぎ", "eel", "unagi.png", "https://ja.wikipedia.org/wiki/ウナギ"),
  new Item("鱧", "はも", "pike conger", "hamo.png", "https://ja.wikipedia.org/wiki/ハモ"),
  new Item("鰯", "いわし", "sardine", "iwashi.png", "https://ja.wikipedia.org/wiki/イワシ"),
  new Item("鯡", "にしん", "herring", "nishin.png", "https://ja.wikipedia.org/wiki/ニシン"),
  new Item("鮎", "あゆ", "sweetfish", "ayu.png", "https://ja.wikipedia.org/wiki/アユ"),
  new Item("鮭", "さけ", "salmon", "sake.png", "https://ja.wikipedia.org/wiki/サケ"),
  new Item("鱒", "にじます", "trout", "nijimasu.png", "https://ja.wikipedia.org/wiki/ニジマス"),
  new Item("鱈", "たら", "cod", "tara.png", "https://ja.wikipedia.org/wiki/タラ"),
  new Item("鱸", "すずき", "sea bass", "suzuki.png", "https://ja.wikipedia.org/wiki/スズキ_(魚)"),
  new Item("鯵", "あじ", "horse mackerel", "aji.png", "https://ja.wikipedia.org/wiki/アジ"),
  new Item("鰤", "ぶり", "yellowtail", "buri.png", "https://ja.wikipedia.org/wiki/ブリ"),
  new Item("鯛", "たい", "sea bream", "tai.png", "https://ja.wikipedia.org/wiki/鯛"),
  new Item("鱩", "はたはた", "sailfin sandfish", "hatahata.png", "https://ja.wikipedia.org/wiki/ハタハタ"),
  new Item("鯖", "さば", "mackerel", "saba.png", "https://ja.wikipedia.org/wiki/サバ"),
  new Item("鮪", "まぐろ", "tuna", "maguro.png", "https://ja.wikipedia.org/wiki/マグロ"),
  new Item("鰹", "かつお", "skipjack tuna", "katsuo.png", "https://ja.wikipedia.org/wiki/カツオ"),
  new Item("鰆", "さわら", "spanish mackerel", "sawara.png", "https://ja.wikipedia.org/wiki/サワラ"),
  new Item("鮃", "ひらめ", "bastard halibut", "hirame.png", "https://ja.wikipedia.org/wiki/ヒラメ"),
  new Item("鰈", "かれい", "flounder", "karei.png", "https://ja.wikipedia.org/wiki/カレイ"),
  new Item("鮑", "あわび", "abalone", "awabi.png", "https://ja.wikipedia.org/wiki/アワビ"),
  new Item("鯏", "あさり", "short-neck clam", "asari.png", "https://ja.wikipedia.org/wiki/アサリ"),
  new Item("鰐", "わに", "alligator/crocodile", "wani.png", "https://ja.wikipedia.org/wiki/ワニ"),
]

const birds = [
  new Item("鷺", "さぎ", "heron", "sagi.png", "https://ja.wikipedia.org/wiki/サギ"),
  new Item("鸛", "こうのとり", "oriental stork", "kounotori.png", "https://ja.wikipedia.org/wiki/コウノトリ"),
  new Item("鴇", "とき", "crested ibis", "toki.png", "https://ja.wikipedia.org/wiki/トキ"),
  new Item("鴨", "かも", "duck", "kamo.png", "https://ja.wikipedia.org/wiki/カモ"),
  new Item("鶩", "あひる", "domestic duck", "ahiru.png", "https://ja.wikipedia.org/wiki/アヒル"),
  new Item("鳶", "とび", "black kite", "tobi.png", "https://ja.wikipedia.org/wiki/トビ"),
  new Item("鷲", "わし", "eagle", "washi.png", "https://ja.wikipedia.org/wiki/鷲"),
  new Item("鷹", "たか", "hawk", "taka.png", "https://ja.wikipedia.org/wiki/鷹"),
  new Item("鶻", "はやぶさ", "peregrine falcon", "hayabusa.png", "https://ja.wikipedia.org/wiki/ハヤブサ"),
  new Item("鶉", "うずら", "japanese quail", "uzura.png", "https://ja.wikipedia.org/wiki/ウズラ"),
  new Item("鶏", "にわとり", "japanese quail", "niwatori.png", "https://ja.wikipedia.org/wiki/ニワトリ"),
  new Item("鴴", "ちどり", "plover", "chidori.png", "https://ja.wikipedia.org/wiki/チドリ科"),
  new Item("鴎", "かもめ", "common gull", "kamome.png", "https://ja.wikipedia.org/wiki/カモメ科"),
  new Item("鳩", "はと", "dove/pigeon", "hato.png", "https://ja.wikipedia.org/wiki/鳩"),
  new Item("鴞", "ふくろう", "owl", "fukurou.png", "https://ja.wikipedia.org/wiki/フクロウ"),
  new Item("鴷", "きつつき", "woodpecker", "kitsutsuki.png", "https://ja.wikipedia.org/wiki/キツツキ科"),
  new Item("鷚", "ひばり", "eurasian skylark", "hibari.png", "https://ja.wikipedia.org/wiki/ヒバリ科"),
  new Item("鵯", "ひよどり", "bulbul", "hiyodori.png", "https://ja.wikipedia.org/wiki/ヒヨドリ"),
  new Item("鵙", "もず", "bull-headed shrike", "mozu.png", "https://ja.wikipedia.org/wiki/モズ"),
  new Item("鴬", "うぐいす", "japanese bush warbler", "uguisu.png", "https://ja.wikipedia.org/wiki/ウグイス"),
  new Item("鶲", "ひたき", "old world flycatcher", "hitaki.png", "https://ja.wikipedia.org/wiki/ヒタキ上科"),
  new Item("鴉", "からす", "crow", "karasu.png", "https://ja.wikipedia.org/wiki/カラス"),
]

export { fish, birds }